
analyzer:
  errors:
    use_build_context_synchronously: warning
    deprecated_member_use: info
    unnecessary_overrides: warning
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true

